### ISSUE TITLE
Crash with Rftools and ABODBB

### ISSUE THREAD

**Issue by ivardensphere** [Bengsch85/TheOminousDark#1]
Crashes the server when a dimlet is made and oreberry bushes from ABODDBB spawn.

Posted the crash on ganymedes01 github.

https://github.com/ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes/issues/13

**Comment by Bengsch85** [comment]
Fixed in newer version of AOBD by Ganymedes:
-Fix worldgen crash with RFTools and other mods that add dimensions.

Will close issue when pack is updated

**Comment by ivardensphere** [comment]
Fixed!
