### ISSUE TITLE
Liquid Dirt crafting returns the item as null ID, crashes client. Also, not appearing in NEI.

### ISSUE THREAD

**Issue by Thorinair** [Bengsch85/TheOminousDark#12]
![image](https://cloud.githubusercontent.com/assets/7534126/8413425/9843e7ba-1e90-11e5-92bc-a996c493bea5.png)
There is currently an issue with Liquid Dirt where it is impossible to see it in NEI, and crafting it will crash the client. It appears that the mod was built using an outdated version of Forge.

**Comment by ivardensphere** [comment]
This is because liquid dirt was built using an old forge before the fluid handler change.

I posted on his bitbucket the issue but he has been inactive a while so this may be pulled out of the pack.

https://bitbucket.org/ace5852/liquid-dirt/issue/1/does-not-show-up-in-nei-and-the-id-is-1

**Comment by ivardensphere** [comment]
Removed from pack.
