### ISSUE TITLE
Food stacking issues.

### ISSUE THREAD

**Issue by Thorinair** [Bengsch85/TheOminousDark#13]
The food items, including Slimeballs, Gelatinous Slime and all edible items are doing weird things when stacking. Mainly, the items will sometimes be stackable to 16, sometimes to 64 seemingly randomly. Probably a race condition between Hunger Overhaul and something else. The same bug causes food to sometimes stack to only one as it is trying to handle a 64 stack, or right clicking to separate stack also causes weird issues.

A related bug seems to happen with Better Barrels, as they will instead stack food items to a maximum of 64x16 and showing a maximum of 1024 when mouse overing. However, they can still actually stack up to 64x64, as the maximum count will be able to go OVER 1024. I had my barrels go to 1500/1024, however this is not shown correctly. The first attached image shows a barrel before taking a stack out, the second shows after taking a stack out.

![image](https://cloud.githubusercontent.com/assets/7534126/8428207/4ea47754-1f1d-11e5-96e3-792815c84daf.png)
![image](https://cloud.githubusercontent.com/assets/7534126/8428235/8005bec0-1f1d-11e5-9bf0-effb7c97424d.png)

**Comment by ivardensphere** [comment]
Fixed in the upcoming update.

**Comment by ivardensphere** [comment]
Fixed!
