### ISSUE TITLE
When spending an item stack, new one is not correctly placed in hand.

### ISSUE THREAD

**Issue by Thorinair** [Bengsch85/TheOminousDark#14]
As the title says, when I spend a full stack of some block, the next one is placed in my hand very weirdly. This issue seems to happen when there are more than 1 stacks remaining in inventory, but not on action bar. Instead of just one "plop" sound, two are heard (and the stack flashes twice on the action bar), and when I try to open my inventory, the second stack will be on my cursor (like I picked it up with my mouse). This often causes awkward dropping of items, especially in caves and such.

The easy way to replicate this is to have 2 stacks of 64 stone (in your inventory, not on your action bar!) and 1 stack of only 1 stone on the action bar. Place that one stone, and see what happens. Attached screenshots demonstrate the issue. The first one shows how the inventory is initially, second is after placing one stone, third is the inventory afterwards.

![image](https://cloud.githubusercontent.com/assets/7534126/8428544/990f97b8-1f1f-11e5-8f16-c63b3f1b5693.png)
![image](https://cloud.githubusercontent.com/assets/7534126/8428549/a3af6536-1f1f-11e5-91fb-9910578ac2d8.png)
![image](https://cloud.githubusercontent.com/assets/7534126/8428557/ae9d9cb0-1f1f-11e5-8129-b11ab0c40ad0.png)

**Comment by ivardensphere** [comment]
Not fixable and won't be.

https://github.com/Kobata/inventory-tweaks/issues/259
