### ISSUE TITLE
Crash and Corruption with RotaryCraft workbenches

### ISSUE THREAD

**Issue by ivardensphere** [Bengsch85/TheOminousDark#3]
Crash and world corruption when disassembling things in a workbench.

**Comment by Bengsch85** [comment]
I cant reproduce in SSP no matter what I try to do. Common fix is to revert to beta rv-2 build 33 but other mods will not support that version of AE2.

**Comment by ivardensphere** [comment]
Fixed in RotaryCraft v7f.
