### ISSUE TITLE
Bug with rftools modules all turning into featherfall modules when crafted.

### ISSUE THREAD

**Issue by ivardensphere** [Bengsch85/TheOminousDark#6]
I beleive this bug ties into RotaryCraft because when removed on a local test base the bug is not there.

A quick dirty fix would be to minetweak all the recipes for modules.

**Comment by Jhary** [comment]
Created new recipes for the different modules of the environmental controller. That fixes our problem here. Also made them a bit harder to craft.
Submitted a pull request to merge this in.
